# Configuration for database settings
database:
  # Specify the database module to use [SQLite, MySQL]
  module: 'SQLite'

  # Configuration for SQLite
  SQLite:
    # Path to the SQLite database file
    # Note: Place the SQLite database file in the plugin's data folder
    path: '%plugin_name%.db'

  # Configuration for MySQL
  MySQL:
    # JDBC connection string for MySQL database
    # If provided, other MySQL settings below are not required
    connection-string: 'jdbc:mysql://root:password@127.0.0.1:3306/server_db'

    # MySQL server address and port
    endpoint: "127.0.0.1:3306"

    # Name of the MySQL database
    database-name: 'server_db'

    # MySQL user credentials
    username: 'root'
    password: 'password'
