name: Build Plugin

on:
  workflow_run:
    workflows: [ "Tag on Main Push" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  check-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: tag
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_ENV"
          echo "Latest tag is $LATEST_TAG"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.LATEST_TAG }}
          files: target/*.jar
          body: |
            ## Installation via JitPack

            Add JitPack to your repositories:
            ```xml
            <repositories>
              <repository>
                <id>jitpack.io</id>
                <url>https://jitpack.io</url>
              </repository>
            </repositories>
            ```

            Add the dependency:
            ```xml
            <dependency>
              <groupId>com.github.hubailmn</groupId>
              <artifactId>Utility</artifactId>
              <version>${{ env.LATEST_TAG }}</version>
            </dependency>
            ```

            ---
            > **Version**: `${{ env.LATEST_TAG }}`
          draft: false
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
