name: Tag on Main Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          if [ -z "$LATEST_TAG" ]; then
            echo "No valid semver tag found. Using v1.0.0 as base."
            LATEST_TAG="v1.0.0"
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_ENV"
          echo "Latest tag: $LATEST_TAG"

      - name: Bump patch and push new tag
        run: |
          VERSION="${LATEST_TAG#v}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "Creating new tag: $NEW_TAG"

          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
        env:
          LATEST_TAG: ${{ env.LATEST_TAG }}
